In [1]:
import numpy as np

In [2]:
x = np.array([2 for _ in range(4)])

In [4]:
type(x)

numpy.ndarray

In [8]:
x @ x.T

16

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
x = np.array([1,2,3,4,5,6])
x.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
y = np.array([i for i in range(1, 9)])
y = y.reshape((2,-1))
b = np.array([1,2])

In [37]:
np.expand_dims(b,1).shape

(2, 1)

In [36]:
y+np.expand_dims(b,1)

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])