In [6]:
import numpy as np

In [2]:
x = np.array([2 for _ in range(4)])

In [4]:
type(x)

numpy.ndarray

In [8]:
x @ x.T

16

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
x = np.array([1,2,3,4,5,6])
x.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [2]:
y = np.array([i for i in range(1, 9)])
y = y.reshape((2,-1))
b = np.array([1,2])

In [3]:
np.expand_dims(b,1).shape

(2, 1)

In [4]:
z = y+np.expand_dims(b,1)

In [5]:
print(f"shape of matrix: {z.shape}")
print(f"sum of elements spread out through the columns and rows, respectively: {z.sum(axis = 0)} & {z.sum(axis = 1)}")
print(f"mean of elements spread out through the columns and rows, respectively: {z.mean(axis = 0)} & {z.mean(axis = 1)}")

shape of matrix: (2, 4)
sum of elements spread out through the columns and rows, respectively: [ 9 11 13 15] & [14 34]
mean of elements spread out through the columns and rows, respectively: [4.5 5.5 6.5 7.5] & [3.5 8.5]


In [9]:
z = np.zeros(5)+2
z

array([2., 2., 2., 2., 2.])

In [13]:
np.array([[1,2,3],[4,5,6]]) @ np.array([[7,8],[9,10],[11,12]])

array([[ 58,  64],
       [139, 154]])

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Turtle fidget spinner
`Hint: keep pressing space bar`

In [2]:
from turtle import *

state = {'turn':0}

def spinner():
    clear()
    angle = state['turn']/10
    right(angle)
    forward(100)
    dot(120, 'red')
    back(100)

    right(120)
    forward(100)
    dot(120, 'green')
    back(100)

    right(120)
    forward(100)
    dot(120, 'blue')
    back(100)

    right(120)
    update()



def animate():
    if state['turn']>0:
        state['turn']-=1
    spinner()
    ontimer(animate, 20)

def flick():
    state['turn']+=10


setup(420, 420, 370, 0)
hideturtle()
tracer(False)
width(20)
onkey(flick,'space')
listen()
animate()
done()